{% set name = "termgraph" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8bda932a1e3e121e9a3b5f3f267c85ca7c344fdbc60883e340509bc4af2bc4ee

build:
  number: 0
  noarch: python
  entry_points:
    - termgraph=termgraph.termgraph:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - colorama

test:
  requires:
    - python {{ python_min }}
  imports:
    - termgraph
  commands:
    - termgraph --help

about:
  home: https://github.com/mkaz/termgraph
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: a python command-line tool which draws basic graphs in the terminal

extra:
  recipe-maintainers:
    - xhochy
