{% set name = "termgraph" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2db4b8195418b05e21544e04ffbe21250ffc83b5d33b3faee3222dda95084b1e

build:
  number: 0
  noarch: python
  entry_points:
    - termgraph=termgraph.termgraph:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - colorama

test:
  requires:
    - python {{ python_min }}
  imports:
    - termgraph
  commands:
    - termgraph --help

about:
  home: https://github.com/mkaz/termgraph
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: a python command-line tool which draws basic graphs in the terminal

extra:
  recipe-maintainers:
    - xhochy
